Upgrade to GitLab CE 15.5.0
sameersbn/docker-gitlab pull request #2648
Opened 2022-10-21 09:18 UTC by antt1995

2022-10-21 17:12 UTC, sachilles commented
@antt1995 Wow, that's fast. Still, I think we should wait for the official release. (Tomorrow will be the day).

2022-10-23 07:23 UTC, sachilles commented on Dockerfile
>      GITLAB_SHELL_VERSION=14.10.0 \
Please upgrade to 14.12.0.

2022-10-23 07:25 UTC, sachilles commented on Changelog.md
> +
Please add 

- gitlab-shell: upgrade to v14.12.0

2022-10-23 07:26 UTC, sachilles requested changes
Please update the gitlab-shell packages.

2022-10-23 11:33 UTC, antt1995 commented
@sachilles All done as requested

2022-10-23 13:01 UTC, sachilles approved these changes
Many thanks!

2022-10-23 13:01 UTC, merged