Upgrade to GitLab CE 15.3.5
sameersbn/docker-gitlab pull request #2655
Opened 2022-11-02 15:55 UTC by antt1995

2022-11-03 19:35 UTC, sachilles requested changes
Please check my comments. Thank you in advance.

2022-11-03 19:35 UTC, sachilles commented on Changelog.md
> +
Could you be so kind and add

    ubuntu: upgrade to focal-20220922

(See my comment related to the Dockerfile.)

2022-11-03 19:35 UTC, sachilles commented on Dockerfile
>  FROM ubuntu:focal-20220826
Could you be so kind and use the base image ubuntu:focal-20221019? (Just to reduce the docker image size.)

2022-11-03 21:54 UTC, antt1995 commented
@sachilles As Requested

2022-11-04 04:32 UTC, sachilles approved these changes
LGTM! Thanks.

2022-11-04 04:33 UTC, merged